x-baseService: &baseService
  restart: always
  healthcheck:
    interval: 1s
    timeout: 2s
    retries: 100

services:
  gateway:
    container_name: gateway
    <<: *baseService
    image: nginx
    volumes:
      - ./nginx.dev.conf:/etc/nginx/nginx.conf
    ports:
      - ${GATEWAY_PORT}:80
    depends_on:
      backend:
        condition: service_healthy
      frontend:
        condition: service_healthy

  backend:
    container_name: backend
    <<: *baseService
    build:
      context: ./backend
      dockerfile: Dockerfile.dev
    devices:
      - /dev/hidraw1:/dev/hidraw1
      - /dev/bus/usb:/dev/bus/usb
      - /dev/ttyUSB0:/dev/ttyUSB0
    ports:
      - "3001:3001"
    healthcheck:
      test:
        [
          "CMD-SHELL",
          "curl --fail --request GET --url 'http://backend:3001/api/health' || exit 1",
        ]
    volumes:
      - ./backend/src:/app/src/
      - /run/pcscd:/run/pcscd
    environment:
      BADGE_TYPE: ${BADGE_TYPE}
      LOCKER_TYPE: ${LOCKER_TYPE}
      NFC_TYPE: ${NFC_TYPE}
      SERIAL_TYPE: ${SERIAL_TYPE}
      DB_PASSWORD: ${DB_PASSWORD}
      DB_DATABASE: ${DB_DATABASE}
      DB_USER: ${DB_USER}
      DB_HOST: ${DB_HOST}
      # SERIAL_PATH: ${SERIAL_PATH}
      # TIMEOUT_STATUS: ${TIMEOUT_STATUS}
      # TIMEOUT_RESERVATION: ${TIMEOUT_RESERVATION}

  frontend:
    container_name: frontend
    <<: *baseService
    build:
      context: ./frontend
      dockerfile: Dockerfile.dev
    healthcheck:
      test:
        [
          "CMD-SHELL",
          "curl --fail --request GET --url 'http://frontend:5173' || exit 1",
        ]
    volumes:
      - ./frontend/src:/app/src/
    environment:
      VITE_API_URL: ${VITE_API_URL}
      VITE_WS_URL: ${VITE_WS_URL}

  database:
    container_name: database
    <<: *baseService
    image: postgres
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -d ${DB_DATABASE} -U ${DB_USER}"]
    volumes:
      - ./persist/db-dev:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_DATABASE}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_HOST: ${DB_HOST}
